[package]
name = "author"
version = "0.1.0"
authors = ["JakeSCahill <jake.cahill@iota.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.32", default-features = false }
iota-streams = { path = "../streams" }
failure = "0.1"
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "03cf531" }